// Auto-generated by LibreLane
module yolo26n_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clock,
  input reset,
  input start,
  output done,
  output busy,
  output[4:0] current_stage,
  input host_input_we,
  input[20:0] host_input_addr,
  input[31:0] host_input_data,
  input[10:0] host_output_addr,
  output[31:0] host_output_data
);
endmodule
